package com.example;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
/**
 * Represents a single transfer between two accounts or, a deposit or withdrawal from a single account.
 * A withdrawal is represented by having a null giving account.
 * A deposit is represented by having a null recieving account.
 * A blank transaction can be generated by setting both recievingAccount and givingAccount to null.
 * @author Mathiue Bernardin
 */
public class Transaction{
    /**
     * The unique ID of this transaction.
     */
    private String transactionID;
    /**
     * The amount involved in this transaction.
     */
    private double amnt;
    /**
     * The ID of the account on the recieving end of this transaction, where applicable.
     */
    private String receivingAccount;
    /**
     * The ID of the account on the giving end of this tr ansaction, where applicable.
     */
    private String givingAccount;
    /**
     * The date and time of this transaction.
     */
    private LocalDateTime date;
    /**
     * The date of this transaction.
     */
    private LocalDate simpleDate; 
    /**
     * Constructor for this class. Automatically generates an ID (type (3,0)).
     * @param amnt - the amount involved in this transaction.
     * @param receivingAccount - the ID of the account on the recieving end of this transaction, where applicable.
     * @param givingAccount - the ID of the account on the giving end of this tr ansaction, where applicable.
     * @throws InvalidTypeException if something goes wrong.
     */
    public Transaction(double amnt, String receivingAccount, String givingAccount) throws InvalidTypeException {
        boolean validID=false;
        while(!validID){
            transactionID=IdCreator.createID(3,0);
            if(!App.driver.exists(transactionID))validID=true;
        }
        if(receivingAccount==null&&givingAccount==null){
            date=LocalDateTime.ofEpochSecond(0, 0, null);
            simpleDate=LocalDate.ofEpochDay(0);
        }
        else{
            date=LocalDateTime.now();
            simpleDate=LocalDate.now();
        }
        this.amnt = amnt;
        this.receivingAccount = receivingAccount;
        this.givingAccount = givingAccount;
    }
    /**
     * Gets the date and time this transaction was made.
     * @return this transaction's date.
     */
    public LocalDateTime getDateTime() {
        return date;
    }
    /**
     * Gets this transaction's unique ID.
     * @return this transaction's ID.
     */
    public String getTransactionID() {
        return transactionID;
    }
    /**
     * Gets a representation of this transaction as a String.
     * Formatted differently depending on what kind of transaction is being represented.
     * @return the representation of this transaction.
     */
    @Override
    public String toString() {
        if(givingAccount==null&&receivingAccount==null)return "No more transactions to show...";
        if(receivingAccount==null)return "("+simpleDate+") Withdrawal from account no. "+givingAccount+" of "+amnt+"$";
        if(givingAccount==null)return "("+simpleDate+") Deposit to account no. "+receivingAccount+" of "+amnt+"$";
        return "("+simpleDate+") Transfer from account no. "+givingAccount+" to account no. "+receivingAccount+" of "+amnt+"$";
    }
    /**
     * Checks if an account is associated (i.e. is on the giving or recieving end) of this transaction.
     * @param accountID - the ID of the account to be checked. 
     * @return true if it is; false otherwise.
     */
    public boolean isAssociatedTo(String accountID){
        if(accountID==null)return false;
        if(givingAccount==null&&receivingAccount==null)return true;
        if(givingAccount!=null){
            if(givingAccount.equals(accountID))return true;
        }
        if(receivingAccount!=null){
            if(receivingAccount.equals(accountID))return true;
        }
        return false;
    }
}